export const providerLogos: Record<string, string> = {
  "Tubi": "/providers/tubi.png",
  "Tubi TV": "/providers/tubi.png",
  "Pluto TV": "/providers/pluto-tv.png",
  "Freevee": "/providers/freevee.png",
  "Amazon Freevee": "/providers/freevee.png",
  "Peacock": "/providers/peacock.png",
  "Roku Channel": "/providers/roku-channel.png",
  "The Roku Channel": "/providers/roku-channel.png",
  "CBC Gem": "/providers/cbc-gem.png",
  "MAX Free": "/providers/max.png",
  "All 4": "/providers/all-4.png",
  "Fawesome": "/providers/fawesome.png",
  "YouTube Premium Free Tier": "/providers/youtube.png",
  "YouTube": "/providers/youtube.png",
  "Plex": "/providers/plex.png",
  "PBS": "/providers/pbs.png",
  "Syfy": "/providers/syfy.png",
  "7plus": "/providers/7plus.png",
  "9Now": "/providers/9now.png",
  "Crunchyroll": "/providers/crunchyroll.png",
  "Popcornflix": "/providers/popcornflix.png",
  "Shout! Factory TV": "/providers/shout-factory-tv.png",
  "South Park Studios": "/providers/south-park-studios.png",
  "Hoopla": "/providers/hoopla.png",
  "The CW": "/providers/the-cw.png",
  "CW": "/providers/the-cw.png",
  "FX": "/providers/fx.png",
  "NBC": "/providers/nbc.png",
  "Kanopy": "/providers/kanopy.png",
  "Adult Swim": "/providers/adult-swim.png",
  "Spectrum On Demand": "/providers/spectrum-on-demand.png",
  "Spectrum": "/providers/spectrum-on-demand.png",
  "Prime Video": "/providers/prime-video.png",
  "Amazon Prime Video": "/providers/prime-video.png",
  "Hulu": "/providers/hulu.png",
  "hulu": "/providers/hulu.png",
  "Vudu": "/providers/vudu.png",
  "vudu": "/providers/vudu.png",
  "TNT": "/providers/tnt.png",
  "tnt": "/providers/tnt.png",
  "Netflix": "/providers/netflix.png",
  "netflix": "/providers/netflix.png",
  "Disney+": "/providers/disney-plus.png",
  "disney plus": "/providers/disney-plus.png",
  "Disney Plus": "/providers/disney-plus.png",
  "Apple TV": "/providers/apple-tv.png",
  "appletv": "/providers/apple-tv.png",
  "FuboTV": "/providers/fubo-tv.png",
  "fubo": "/providers/fubo-tv.png",
  "MGM+": "/providers/mgm-plus.png",
  "mgm plus": "/providers/mgm-plus.png",
  "Paramount+": "/providers/paramount-plus.png",
  "paramount plus": "/providers/paramount-plus.png",
  "My5": "/providers/my5.png",
  "my5": "/providers/my5.png",
  "ITVX": "/providers/itvx.png",
  "ITV Player": "/providers/itvx.png",
  "ITV": "/providers/itvx.png",
  "CBS": "/providers/cbs.png",
  "UKTV Play": "/providers/uktv-play.png",
  "UKTV": "/providers/uktv-play.png",
  "BBC iPlayer": "/providers/bbc-iplayer.png",
  "BBC": "/providers/bbc-iplayer.png",
  "iPlayer": "/providers/bbc-iplayer.png",
  "Rakuten TV": "/providers/rakuten-tv.png",
  "Rakuten": "/providers/rakuten-tv.png",
};
